require: rubocop-rails
AllCops:
  Exclude:
    - db/**
    - config/**/*
    - script/**
    - bin/**
    - tmp/**

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - spec/**/*