version: "3.7"
services:
  db:
    image: postgres:13.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypass
  web:
    build: .
    environment:
      DATABASE_URL: "postgres://user:mypass@dbhost/"
      JWT_SECRET: "123456"
    links:
      - db:dbhost
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db